### ISSUE TITLE
REQ: Auto upvoting question upon upvoting answer

### ISSUE THREAD

**Issue by BusiBeaver** [userscripters/voting-overcharged#7]
snip

**Comment by double-beep** [comment]
I don't think that's a good idea. Votes should be based on each post's content, not on the score of the parent question/child answers.

**Comment by BusiBeaver** [comment]
**<ins>1. This feature request was raised with considering only Puzzling.SE (PSE)</ins>**, the only SE community I hang out in. Two big differences between PSE and other SE communities are:

- Most (if not all) questions are posted not because the OP doesn't know the answer.

- Most (if not all) questions don't arise naturally out of curiosity (why does the sun rise in the east?), but are deliberately ***designed*** to challenge (giving fun to) solvers.

These two characteristics make it difficult (if not impossible) for a poor designed/constructed puzzle to spawn a good answer at PSE. Actually, I just checked voting logs, my last 40 upvotes on answers have invariably all (or should) been accompanied by upvotes on their questions, 17 out of which should, but I forgot. I feel bad for forgetting to give the questioner (puzzle designer or sharer) the upvotes they deserve.

**<ins>2. I agree, for SO (or other potential SE sub-communities), this feature might not fit well.</ins>**

**<ins>3. Search for a solution that both sides happy</ins>**

- What do you think if this feature works at the granularity of sub-community (Enabled on PSE, Disabled on SO and by default)?
- Or (optionally) instead of casting votes, but creates a reminder that pops out (Do you think the question that spawned this answer deserves an upvote as well?) like [the one when we downvote questions](https://meta.stackexchange.com/a/2373))?
- Or a combination of these two?

Regardless, It's understandable if this feature is rejected for too few beneficiaries, or development costs outweighed benefits.
